[package]
name = "tshock-to-plr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
rusqlite = { version = "0.32.0", features = ["bundled"] }
terra-items = "0.2.3"
terra-plr = "0.2.0"
terra-types = "0.2.2"
